import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  restaurants: defineTable({
    name: v.string(),
    address: v.string(),
    phone: v.optional(v.string()),
    hours: v.any(),
    createdAt: v.number()
  }),
  restaurantPolicies: defineTable({
    restaurantId: v.id("restaurants"),
    reservationWindowDays: v.number(),
    maxAutomaticPartySize: v.number(),
    depositRequiredPartySize: v.union(v.number(), v.null()),
    depositAmountCents: v.union(v.number(), v.null()),
    cancellationCutoffHours: v.number(),
    outsideCakeAllowed: v.union(v.boolean(), v.null()),
    outsideCakeFeeCents: v.union(v.number(), v.null()),
    allergyStatement: v.string()
  }).index("by_restaurant", ["restaurantId"]),
  restaurantKnowledge: defineTable({
    restaurantId: v.id("restaurants"),
    category: v.string(),
    title: v.string(),
    body: v.string(),
    source: v.string(),
    updatedAt: v.number()
  }).index("by_restaurant", ["restaurantId"]),
  customers: defineTable({
    name: v.optional(v.string()),
    phone: v.optional(v.string()),
    email: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number()
  }),
  conversations: defineTable({
    externalId: v.string(),
    restaurantId: v.id("restaurants"),
    customerId: v.optional(v.id("customers")),
    status: v.string(),
    memory: v.any(),
    updatedAt: v.number()
  }).index("by_external_id", ["externalId"]),
  messages: defineTable({
    conversationId: v.id("conversations"),
    role: v.string(),
    text: v.string(),
    channel: v.string(),
    createdAt: v.number()
  }).index("by_conversation", ["conversationId"]),
  agentRuns: defineTable({
    conversationId: v.id("conversations"),
    restaurantId: v.id("restaurants"),
    status: v.string(),
    customerRequest: v.string(),
    plan: v.optional(v.any()),
    modelCallCount: v.number(),
    estimatedCostCents: v.number(),
    startedAt: v.number(),
    completedAt: v.optional(v.number())
  }).index("by_conversation", ["conversationId"]),
  agentTasks: defineTable({
    runId: v.id("agentRuns"),
    taskId: v.string(),
    specialist: v.string(),
    runtimeRoleName: v.string(),
    status: v.string(),
    objective: v.string(),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number())
  }).index("by_run", ["runId"]),
  handoffs: defineTable({
    runId: v.id("agentRuns"),
    taskId: v.string(),
    roleName: v.string(),
    payload: v.any(),
    createdAt: v.number()
  }).index("by_run", ["runId"]),
  specialistResults: defineTable({
    runId: v.id("agentRuns"),
    taskId: v.string(),
    roleName: v.string(),
    result: v.any(),
    attempt: v.number(),
    createdAt: v.number()
  }).index("by_run", ["runId"]),
  pendingConfirmations: defineTable({
    runId: v.id("agentRuns"),
    conversationId: v.id("conversations"),
    restaurantId: v.id("restaurants"),
    customerId: v.optional(v.id("customers")),
    token: v.string(),
    action: v.string(),
    payload: v.any(),
    status: v.string(),
    createdAt: v.number(),
    expiresAt: v.number()
  })
    .index("by_run", ["runId"])
    .index("by_token", ["token"]),
  runEvents: defineTable({
    runId: v.id("agentRuns"),
    type: v.string(),
    summary: v.string(),
    data: v.any(),
    createdAt: v.number()
  }).index("by_run", ["runId"]),
  reservations: defineTable({
    restaurantId: v.id("restaurants"),
    customerId: v.optional(v.id("customers")),
    runId: v.id("agentRuns"),
    name: v.string(),
    contact: v.string(),
    date: v.string(),
    time: v.string(),
    partySize: v.number(),
    specialRequests: v.optional(v.string()),
    status: v.string(),
    confirmationToken: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number()
  }).index("by_customer", ["customerId"]),
  cateringLeads: defineTable({
    restaurantId: v.id("restaurants"),
    runId: v.id("agentRuns"),
    customerName: v.string(),
    contact: v.string(),
    eventType: v.string(),
    dateRange: v.string(),
    guestCount: v.number(),
    notes: v.string(),
    status: v.string(),
    createdAt: v.number()
  }).index("by_restaurant", ["restaurantId"]),
  searchResults: defineTable({
    restaurantId: v.id("restaurants"),
    runId: v.id("agentRuns"),
    query: v.string(),
    response: v.string(),
    sources: v.array(v.any()),
    createdAt: v.number()
  }).index("by_run", ["runId"]),
  checkoutSessions: defineTable({
    reservationId: v.id("reservations"),
    runId: v.id("agentRuns"),
    provider: v.string(),
    providerSessionId: v.string(),
    checkoutUrl: v.string(),
    amountCents: v.number(),
    status: v.string(),
    metadata: v.any(),
    createdAt: v.number(),
    updatedAt: v.number()
  }).index("by_reservation", ["reservationId"])
});
